---
- name: 'remove unofficial packages'
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
    state: absent
    autoremove: true
  become: true

- name: 'add docker gpg key'
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution.lower() }}/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 'a+r'
  register: key
  become: true

- name: 'add docker repository'
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution.lower() }} {{ ansible_distribution_release }} stable
    filename: docker
  when: key.changed
  become: true

- name: 'install packages'
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
  register: install
  become: true

- name: 'start service'
  ansible.builtin.service:
    name: docker
    state: started
  when: install.changed
  become: true
